- name: Copy kubelet config files
  hosts: k3s_cluster
  any_errors_fatal: true
  become: yes
  tasks:
    - name: Copy geth service config file
      copy:
        src: ../../manifests/kubelet-config.yaml
        dest: /home/ubuntu/kubelet-config.yaml
      register: result