- name: Install MetalLB as default LoadBalancer
  hosts: master
  any_errors_fatal: true
  become: true
  tasks:
    - name: Install MetalLB from kubectl
      shell: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/namespace.yaml && \
             kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml && \
             kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
    - name: Copy MetalLB config to server
      template:
        src: ../manifests/metallb-config.yaml.j2
        dest: /var/lib/rancher/k3s/server/manifests/metallb-config.yaml
        owner: root
        group: root
        mode: preserve
    - name: Explicitly apply MetalLB config
      shell: kubectl apply -f /var/lib/rancher/k3s/server/manifests/metallb-config.yaml