- name: Copy validator keys to cluster
  hosts: master
  any_errors_fatal: true
  become: true
  tasks:
    - name: Copy lighthouse keys
      copy:
        src: ../eth2_launchpad_files/lighthouse/validator_keys
        dest: /mnt/eth2/.lighthouse
      when: deploy_lighthouse_validator == true
    - name: Restart lighthouse validator
      shell: kubectl rollout restart deployment/lighthouse-validator && kubectl delete pods -l app=lighthouse-validator
      when: deploy_lighthouse_validator == true