- name: Re-enable updates
  hosts: k3s_cluster
  become: yes
  any_errors_fatal: true
  tasks:
    - shell: systemctl enable apt-daily.service && \
             systemctl enable apt-daily.timer && \
             systemctl enable apt-daily-upgrade.timer && \
             systemctl enable apt-daily-upgrade.service